-- FYP Supervision Portal - Supabase schema
-- Run this in Supabase SQL Editor once.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  role text not null default 'student' check (role in ('supervisor','student')),
  created_at timestamptz not null default now()
);

create table if not exists public.academic_years (
  id uuid primary key default gen_random_uuid(),
  label text not null unique,
  start_year int not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.students (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid references public.profiles(id) on delete set null,
  academic_year_id uuid not null references public.academic_years(id) on delete restrict,
  full_name text not null,
  email text not null,
  student_no text,
  created_at timestamptz not null default now(),
  unique(email, academic_year_id)
);

create table if not exists public.projects (
  id uuid primary key default gen_random_uuid(),
  student_id uuid not null unique references public.students(id) on delete cascade,
  title text not null,
  description text,
  semester int not null default 1 check (semester in (1,2)),
  created_at timestamptz not null default now()
);

create table if not exists public.tasks (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  instructions text,
  evidence_requirements text,
  stage text,
  semester int not null default 1 check (semester in (1,2)),
  open_at timestamptz,
  due_at timestamptz not null,
  created_by uuid references public.profiles(id),
  created_at timestamptz not null default now()
);

create table if not exists public.task_assignments (
  id uuid primary key default gen_random_uuid(),
  task_id uuid not null references public.tasks(id) on delete cascade,
  student_id uuid not null references public.students(id) on delete cascade,
  assigned_at timestamptz not null default now(),
  unique(task_id,student_id)
);

create table if not exists public.submissions (
  id uuid primary key default gen_random_uuid(),
  task_id uuid not null references public.tasks(id) on delete cascade,
  student_id uuid not null references public.students(id) on delete cascade,
  summary text,
  results text,
  interpretation text,
  problems text,
  next_action text,
  report_section text,
  external_link text,
  status text not null default 'submitted' check (status in ('submitted','resubmitted','approved','revision_required','incomplete')),
  revision_no int not null default 1,
  submitted_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(task_id,student_id)
);

create table if not exists public.submission_files (
  id uuid primary key default gen_random_uuid(),
  submission_id uuid not null references public.submissions(id) on delete cascade,
  student_id uuid not null references public.students(id) on delete cascade,
  storage_path text not null,
  file_name text not null,
  file_type text,
  file_size bigint,
  uploaded_at timestamptz not null default now()
);

create table if not exists public.feedback (
  id uuid primary key default gen_random_uuid(),
  submission_id uuid not null references public.submissions(id) on delete cascade,
  supervisor_id uuid references public.profiles(id),
  decision text not null check (decision in ('approved','revision_required','incomplete')),
  comment text,
  revision_due_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.audit_events (
  id bigint generated by default as identity primary key,
  actor_id uuid references public.profiles(id),
  entity_type text not null,
  entity_id uuid,
  action text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

-- Create/refresh profile automatically when a user signs up.
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  insert into public.profiles(id,full_name,role)
  values(new.id,coalesce(new.raw_user_meta_data->>'full_name',new.email),'student')
  on conflict(id) do nothing;

  update public.students
  set profile_id=new.id
  where lower(email)=lower(new.email) and profile_id is null;
  return new;
end; $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.is_supervisor()
returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='supervisor');
$$;

create or replace function public.current_student_id()
returns uuid language sql stable security definer set search_path=public as $$
  select s.id from public.students s
  where s.profile_id=auth.uid() or lower(s.email)=lower(coalesce(auth.jwt()->>'email',''))
  order by s.created_at desc limit 1;
$$;

-- RLS
alter table public.profiles enable row level security;
alter table public.academic_years enable row level security;
alter table public.students enable row level security;
alter table public.projects enable row level security;
alter table public.tasks enable row level security;
alter table public.task_assignments enable row level security;
alter table public.submissions enable row level security;
alter table public.submission_files enable row level security;
alter table public.feedback enable row level security;
alter table public.audit_events enable row level security;

create policy "profiles own or supervisor read" on public.profiles for select using (id=auth.uid() or public.is_supervisor());
create policy "profiles own update" on public.profiles for update using (id=auth.uid()) with check (id=auth.uid());

create policy "academic years authenticated read" on public.academic_years for select to authenticated using (true);
create policy "academic years supervisor write" on public.academic_years for all to authenticated using (public.is_supervisor()) with check (public.is_supervisor());

create policy "students own or supervisor read" on public.students for select to authenticated using (public.is_supervisor() or id=public.current_student_id());
create policy "students supervisor write" on public.students for all to authenticated using (public.is_supervisor()) with check (public.is_supervisor());

create policy "projects own or supervisor read" on public.projects for select to authenticated using (public.is_supervisor() or student_id=public.current_student_id());
create policy "projects supervisor write" on public.projects for all to authenticated using (public.is_supervisor()) with check (public.is_supervisor());

create policy "tasks assigned or supervisor read" on public.tasks for select to authenticated using (
  public.is_supervisor() or exists(select 1 from public.task_assignments a where a.task_id=tasks.id and a.student_id=public.current_student_id())
);
create policy "tasks supervisor write" on public.tasks for all to authenticated using (public.is_supervisor()) with check (public.is_supervisor());

create policy "assignments own or supervisor read" on public.task_assignments for select to authenticated using (public.is_supervisor() or student_id=public.current_student_id());
create policy "assignments supervisor write" on public.task_assignments for all to authenticated using (public.is_supervisor()) with check (public.is_supervisor());

create policy "submissions own or supervisor read" on public.submissions for select to authenticated using (public.is_supervisor() or student_id=public.current_student_id());
create policy "students insert own submissions" on public.submissions for insert to authenticated with check (student_id=public.current_student_id());
create policy "students update own submissions" on public.submissions for update to authenticated using (student_id=public.current_student_id() or public.is_supervisor()) with check (student_id=public.current_student_id() or public.is_supervisor());

create policy "submission files own or supervisor read" on public.submission_files for select to authenticated using (public.is_supervisor() or student_id=public.current_student_id());
create policy "submission files student insert" on public.submission_files for insert to authenticated with check (student_id=public.current_student_id());

create policy "feedback own or supervisor read" on public.feedback for select to authenticated using (public.is_supervisor() or exists(select 1 from public.submissions s where s.id=feedback.submission_id and s.student_id=public.current_student_id()));
create policy "feedback supervisor write" on public.feedback for all to authenticated using (public.is_supervisor()) with check (public.is_supervisor());

create policy "audit supervisor read" on public.audit_events for select to authenticated using (public.is_supervisor());
create policy "audit authenticated insert" on public.audit_events for insert to authenticated with check (actor_id=auth.uid());

-- Storage bucket. Private by default; files are opened through signed URLs.
insert into storage.buckets(id,name,public,file_size_limit)
values('fyp-evidence','fyp-evidence',false,52428800)
on conflict(id) do update set public=false,file_size_limit=52428800;

create policy "evidence upload own folder" on storage.objects for insert to authenticated with check (
  bucket_id='fyp-evidence' and (public.is_supervisor() or split_part(name,'/',1)=public.current_student_id()::text)
);
create policy "evidence read own folder or supervisor" on storage.objects for select to authenticated using (
  bucket_id='fyp-evidence' and (public.is_supervisor() or split_part(name,'/',1)=public.current_student_id()::text)
);
create policy "evidence delete own folder or supervisor" on storage.objects for delete to authenticated using (
  bucket_id='fyp-evidence' and (public.is_supervisor() or split_part(name,'/',1)=public.current_student_id()::text)
);

-- IMPORTANT: After you create YOUR account, promote it once in SQL Editor:
-- update public.profiles set role='supervisor' where id=(select id from auth.users where email='YOUR_EMAIL');


-- Meeting booking feature

create table if not exists public.meeting_slots (
  id uuid primary key default gen_random_uuid(),
  start_at timestamptz not null,
  end_at timestamptz not null,
  location text,
  note text,
  created_by uuid references public.profiles(id),
  created_at timestamptz not null default now(),
  check (end_at > start_at)
);

create table if not exists public.meeting_bookings (
  id uuid primary key default gen_random_uuid(),
  slot_id uuid not null unique references public.meeting_slots(id) on delete cascade,
  student_id uuid not null references public.students(id) on delete cascade,
  booked_at timestamptz not null default now(),
  status text not null default 'booked' check (status in ('booked','cancelled','completed'))
);

alter table public.meeting_slots enable row level security;
alter table public.meeting_bookings enable row level security;

create policy "meeting slots authenticated read" on public.meeting_slots for select to authenticated using (true);
create policy "meeting slots supervisor write" on public.meeting_slots for all to authenticated using (public.is_supervisor()) with check (public.is_supervisor());
create policy "meeting bookings own or supervisor read" on public.meeting_bookings for select to authenticated using (public.is_supervisor() or student_id=public.current_student_id());
create policy "students book own meeting" on public.meeting_bookings for insert to authenticated with check (student_id=public.current_student_id());
create policy "meeting bookings supervisor write" on public.meeting_bookings for update to authenticated using (public.is_supervisor()) with check (public.is_supervisor());
